- README.md
Small edit to demonstrate feature branches and pull requests to the team.
> POWR-32 Small change to README.md on the correct branch.

- web/sites/default/config/core.entity_form_display.paragraph.telephone_button.default.yml
- web/sites/default/config/core.entity_view_display.paragraph.telephone_button.default.yml
- web/sites/default/config/core.extension.yml
- web/sites/default/config/field.field.paragraph.telephone_button.field_phone_number.yml
- web/sites/default/config/field.storage.paragraph.field_phone_number.yml
- web/sites/default/config/lightning_core.versions.yml
- web/sites/default/config/paragraphs.paragraphs_type.telephone_button.yml
My awesome new telephone button!
> POWR-46 Initial commit to add telephone button paragraph type.

- web/sites/default/config/core.base_field_override.node.service_location.promote.yml
- web/sites/default/config/core.entity_form_display.node.service_location.default.yml
- web/sites/default/config/core.entity_form_display.paragraph.service_mode.default.yml
- web/sites/default/config/core.entity_view_display.node.service_location.default.yml
- web/sites/default/config/core.entity_view_display.node.service_location.teaser.yml
- web/sites/default/config/core.entity_view_display.paragraph.service_mode.default.yml
- web/sites/default/config/field.field.node.service_location.field_building.yml
- web/sites/default/config/field.field.node.service_location.field_floor.yml
- web/sites/default/config/field.field.node.service_location.field_get_directions.yml
- web/sites/default/config/field.field.node.service_location.field_open_hours.yml
- web/sites/default/config/field.field.paragraph.service_mode.field_service_mode_list.yml
- web/sites/default/config/field.field.paragraph.service_mode.field_step.yml
- web/sites/default/config/field.field.paragraph.service_mode.field_time_to_complete.yml
- web/sites/default/config/field.storage.node.field_building.yml
- web/sites/default/config/field.storage.node.field_floor.yml
- web/sites/default/config/field.storage.node.field_get_directions.yml
- web/sites/default/config/field.storage.node.field_open_hours.yml
- web/sites/default/config/field.storage.paragraph.field_service_mode_list.yml
- web/sites/default/config/field.storage.paragraph.field_step.yml
- web/sites/default/config/field.storage.paragraph.field_time_to_complete.yml
- web/sites/default/config/node.type.service_location.yml
- web/sites/default/config/paragraphs.paragraphs_type.service_mode.yml
- web/sites/default/config/search_api.index.content.yml
- web/sites/default/config/user.role.layout_manager.yml
- web/sites/default/config/views.view.search.yml
> POWR-47 Service location content type

- composer.lock
- vendor/composer/installed.json
- web/core/lib/Drupal.php
- web/core/lib/Drupal/Core/Security/RequestSanitizer.php
- web/core/modules/file/src/Element/ManagedFile.php
Can I get a quick PR review to apply the security upgrade?
> Hotfix to update Drupal to 8.5.3 security update

- .circleci/config.yml
Add a step to remove multidev after the PR is merged into master.
> POWR-162 In CI, remove multidev after merging a pull request

- .circleci/config.yml
Open another PR to fix an issue that prevents deleting multidev site.
> POWR-162 Switch working directory before checking git log.

- composer.json
- composer.lock
Please take a minute to give me a quick review. This hotfix will correct an error you are getting when you run `composer install`.
> Remove pathauto patch that no longer applies; update composer.lock

- .circleci/config.yml
> POWR-190 Add HTTP auth

- README.md
Updated the text to reflect the latest workflow.
> POWR-168 Update README.md

- web/themes/custom/bootstrap_barrio/css/components/site-footer.css
- web/themes/custom/stormy/css/style.css
- web/themes/custom/stormy/templates/layout/page.html.twig
> POWR-199 A few more changes to prep for demo.

- web/sites/default/config/core.entity_form_display.paragraph.fax_button.default.yml
- web/sites/default/config/core.entity_view_display.paragraph.fax_button.default.yml
- web/sites/default/config/field.field.paragraph.fax_button.field_fax_number.yml
- web/sites/default/config/field.field.paragraph.service_step.field_step_action_button.yml
- web/sites/default/config/field.storage.paragraph.field_fax_number.yml
- web/sites/default/config/paragraphs.paragraphs_type.fax_button.yml
- web/themes/custom/stormy/css/style.css
- web/themes/custom/stormy/templates/paragraphs/paragraph--fax-button.html.twig
I used a span tag since this isn't a true button/link. I also set the pointer to display the default black arrow on hover instead of the hand since there's no action tied to this element.
> POWR-215 Create Fax button type and add it to service steps

- .gitignore
- web/sites/default/config/field.field.paragraph.fax_button.field_fax_number.yml
@brittanysmart, can I have you review this one? The field_fax_number.yml file had a conflict when I merged your code. I had to reexport it. I also added a line to the gitignore related to Lando.
> Hotfix-7 correct a merge error from POWR-215 and add app to gitignore.

- web/private/scripts/slack_deploy_notification.php
Test the deploy event on multidev.
> POWR-227 Fix a parameter issue in Slack notification

- composer.json
- composer.lock
@kxwang and @RichardDavies, could you review this PR and we can pull this change into master for you to pull locally?
> Hotfix-9 Update composer.lock to match composer.json.

- web/modules/custom/portland/portland.module
- web/sites/default/config/core.entity_view_display.node.news.teaser.yml
The last build created some weird errors on Dev and in my local. These small changes are to address those errors.
> Hotfix-10 address errors in config import and content admin

- .lando.yml
- composer.json
- composer.lock
- web/modules/custom/portland/config/install/openid_connect.settings.azure.yml
- web/modules/custom/portland/config/schema/portland.schema.yml
- web/modules/custom/portland/portland.info.yml
- web/modules/custom/portland/portland.services.yml
- web/modules/custom/portland/src/Plugin/OpenIDConnectClient/Azure.php
- web/modules/custom/portland/src/Routing/RouteSubscriber.php
- web/modules/custom/portland/src/SecretsReader.php
- web/sites/default/config/core.extension.yml
- web/sites/default/config/lightning_core.versions.yml
- web/sites/default/config/openid_connect.settings.azure.yml
- web/sites/default/config/openid_connect.settings.facebook.yml
- web/sites/default/config/openid_connect.settings.generic.yml
- web/sites/default/config/openid_connect.settings.github.yml
- web/sites/default/config/openid_connect.settings.google.yml
- web/sites/default/config/openid_connect.settings.linkedin.yml
- web/sites/default/config/openid_connect.settings.yml
- web/sites/default/services.yml
I removed one of the database logging messages, only logging when the PANTHEON_ENVIRONMENT variable is unset.
This should hopefully run the workflow script to copy in the secrets.
> POWR-279 OpenID login lockdown POC

- web/sites/default/config/views.view.group_content_menu.yml
Content type field aggregation was grouping on wrong column.
> POWR-288 - fixed aggregation bug

- web/sites/default/config/core.entity_view_display.node.building.search_result.yml
- web/sites/default/config/search_api_page.search_api_page.search_portland_gov.yml
Also hid the Service Location summary field label.
> POWR-401 Update search result building location type to align-left

- web/modules/custom/portland/portland.module
I also noticed that group media wasn't included in the bulk alias update, so I added that too.
> POWR-360 - Update group bulk alias only if shortname changes

- web/sites/default/config/field.field.node.service_location.field_floor.yml
Updated floor field help text for adding service locations.
> POWR-397 updated floor field help text

- web/themes/custom/cloudy/scss/_overrides.scss
Add spacing in line with other elements
> POWR-650 Add sass to unbreak preview links from DOM flow

- web/sites/default/config/core.entity_view_display.media.audio.default.yml
- web/sites/default/config/core.entity_view_display.media.video.default.yml
2 small config changes.
I'm not sure why Display Suite conf options were tacked on. This was from a 100% clean and updated environment, and I only changed the Autoplay checkboxes. Is this a concern?
> POWR-689 turn off audio/video autoplay

- composer.lock
- web/sites/default/config/core.entity_form_display.media.document.default.yml
- web/sites/default/config/core.entity_view_display.media.document.default.yml
- web/sites/default/config/field.field.media.document.field_document_type.yml
- web/sites/default/config/field.storage.media.field_document_type.yml
- web/sites/default/config/taxonomy.vocabulary.document_type.yml
I need this field pushed up to live so that I can add the taxonomy terms to the vocabulary and configure further.
> POWR-730 add document type vocabulary; add type field to document

- web/modules/custom/portland/modules/portland_media_embed_helper/portland_media_embed_helper.module
Added null ref check to prevent error from appearing in log
> POWR-736 - Fixed php error with media embed

- README.md
> POWR-756 Update README.md with new local search instructions

- web/sites/default/config/views.view.user_assigned_to_review.yml
I also changed the sort order to descending in order to show the newest assigned items at the top of the list.
> POWR-703 Correct changed date on items assigned view

- web/sites/default/config/views.view.block_content.yml
- web/sites/default/config/views.view.bureaus_and_offices.yml
- web/sites/default/config/views.view.contact_messages.yml
- web/sites/default/config/views.view.content_by_taxonomy.yml
- web/sites/default/config/views.view.files.yml
- web/sites/default/config/views.view.group_media.yml
- web/sites/default/config/views.view.locked_content.yml
- web/sites/default/config/views.view.media_library.yml
- web/sites/default/config/views.view.my_content.yml
- web/sites/default/config/views.view.my_media.yml
- web/sites/default/config/views.view.redirect.yml
Adding reset buttons to views with exposed filters
> POWR-892 adding reset buttons to views

- .circleci/config.yml
- web/themes/custom/cloudy/templates/views/views-view-unformatted.html.twig
A bug fix to address the empty <h3> created on group/events pages.
> POWR-865 <h3> bug fix

- .circleci/config.yml
- composer.lock
Trying a hotfix suggested by Kevin, removing the module directory before build to get a fresh copy.
> HOTFIX-23 Problems with search_api_solr module deploying

- web/modules/custom/portland/modules/portland_moderation_helper/portland_moderation_helper.info.yml
- web/modules/custom/portland/modules/portland_moderation_helper/portland_moderation_helper.module
- web/sites/default/config/core.extension.yml
- web/sites/default/config/lightning_core.versions.yml
I was able to write a tiny module to handle this faster than I could even figure out how to use the Rules module, so that's the route I went.
> POWR-1072 small custom module to clear reviewer field when node is published

- web/themes/custom/cloudy/scss/_overrides.scss
> POWR-1324 fix float-right text wrapping for media in CKEditor

- web/modules/custom/portland/src/Plugin/Block/RevisionBlock.php
Use regex to provide validation and parsing
> POWR-1577 Refactor revision URL parsing

- web/sites/default/config/core.entity_view_display.group.advisory_group.default.yml
- web/sites/default/config/core.entity_view_display.group.bureau_office.default.yml
- web/sites/default/config/core.entity_view_display.group.elected_official.default.yml
- web/sites/default/config/core.entity_view_display.group.program.default.yml
- web/sites/default/config/core.entity_view_display.group.project.default.yml
- web/themes/custom/cloudy/templates/field/address-plain.html.twig
Templating of address allows for skipping portions like country if needed
> POWR-1597 Enable address templating

- web/modules/custom/portland/modules/portland_leaftlet_maps/portland_leaflet_maps.js
- web/modules/custom/portland/modules/portland_media_embed_helper/portland_media_embed_helper.module
- web/sites/default/config/views.view.media.yml
- web/themes/custom/cloudy/templates/media/media--map.html.twig
Also fixed display bug when multiple geo files are on one page. Fixed thumbnail display in map browser view.
> POWR-1551 Show preview image for Geo File inside CKEditor

- web/themes/custom/cloudy/scss/components/_media.scss
- web/themes/custom/cloudy/templates/field/file-link.html.twig
Set document embeds to wrap and remove bottom margin when embedded as a list item.
> POWR-1311 Update document embed styling

- web/themes/custom/cloudy/templates/field/field--field-end-date.html.twig
- web/themes/custom/cloudy/templates/field/field--field-end-time.html.twig
- web/themes/custom/cloudy/templates/field/field--field-start-date.html.twig
- web/themes/custom/cloudy/templates/field/field--field-start-time.html.twig
Set the default margin to correctly align fields within date group.
> POWR-1677 Remove field bottom margin

- web/modules/custom/portland/modules/portland_groups/portland_groups.module
…reated outside of group context.
> POWR-1709 - fix error when adding inline media entities in a global context

- web/sites/default/config/core.entity_form_display.node.event.default.yml
- web/sites/default/config/core.entity_view_display.node.event.default.yml
- web/sites/default/config/field.field.node.event.field_toggle_multiday.yml
- web/sites/default/config/field.storage.node.field_toggle_multiday.yml
> POWR-1653 add multiday toggle and configure form to use accordion

- web/themes/custom/cloudy/cloudy.info.yml
Testing Instructions:
- https://powr-1817-portlandor.pantheonsite.io
- confirm ckeditor works as before
> POWR-1817: point ckeditor assets at correct css dist

- web/themes/custom/cloudy/pattern-lab/_patterns/09-docs/10-accessibility.twig
- web/themes/custom/cloudy/src/components/accessibility.md
Including accessibility guidelines into patternlab docs for referencing purposes.
> POWR-1816 adding accessibility docs

- web/themes/custom/cloudy/pattern-lab/_patterns/01-components/badge/00-docs.twig
- web/themes/custom/cloudy/pattern-lab/_patterns/01-components/badge/05-main-demo.twig
- web/themes/custom/cloudy/pattern-lab/_patterns/01-components/badge/10-type-variations.twig
- web/themes/custom/cloudy/pattern-lab/css/pattern-scaffolding.css
- web/themes/custom/cloudy/src/components/badge/badge.scss
- web/themes/custom/cloudy/src/components/badge/badge.twig
- web/themes/custom/cloudy/src/components/badge/readme.md
- web/themes/custom/cloudy/src/css/_components.scss
Setting up pattern lab demos for badge, pill badge, and nav alert badge.
To Test-
- Pull down this branch and go to http://portlandor.lndo.site/pattern-lab/?p=viewall-components-badge
- See each badge variant represented
> POWR-1792 Pattern Lab Badge Component

- composer.json
- composer.lock
- web/sites/default/config/core.entity_form_display.media.document.default.yml
- web/sites/default/config/core.entity_form_display.media.image.default.yml
- web/sites/default/config/core.extension.yml
- web/sites/default/config/lightning_core.versions.yml
Configured for use with document and image media types
> POWR-1826 enabled media_entity_file_replace module

- web/sites/default/config/views.settings.yml
- web/sites/default/config/views.view.group_nodes.yml
- web/sites/default/config/views.view.park_finder.yml
- web/sites/default/config/views.view.projects_index.yml
- web/sites/default/config/views.view.services_fullindex.yml
- web/sites/default/config/views.view.solr_search.yml
* add data table to list of content types filterable from group editor
view of content
* Add email address to manage contacts group view
* Fix broken handler in /parks/finder view
* Fix broken handler in /services view
* Audit all the search api page views for missing handlers
* Turn on the views setting to see query performance
> POWR-1961 POWR-1969 POWR-1984 POWR-1953 Bug fixes and small view changes

- .lando.yml
- web/sites/default/config/block.block.citysection.yml
- web/sites/default/config/block.block.parkamenitiesactivities.yml
- web/sites/default/config/block.block.parklocationtype.yml
- web/sites/default/config/block.block.reservationsavailable.yml
- web/sites/default/config/core.entity_view_display.group.project.default.yml
- web/sites/default/config/pathauto.pattern.park_facility.yml
- web/sites/default/config/user.role.alert_editor.yml
- web/sites/default/config/user.role.code_editor.yml
- web/sites/default/config/user.role.council_author.yml
- web/sites/default/config/user.role.council_clerk.yml
- web/sites/default/config/user.role.group_creator.yml
- web/sites/default/config/user.role.park_editor.yml
- web/sites/default/config/user.role.policy_author.yml
- web/sites/default/config/user.role.policy_editor.yml
- web/sites/default/config/user.role.publisher.yml
- web/sites/default/config/user.role.sitewide_editor.yml
- web/sites/default/config/views.view.events_index.yml
- web/sites/default/config/views.view.group_events.yml
- web/sites/default/config/views.view.page_menu.yml
- web/themes/custom/cloudy/templates/groups/advisory-group/group--advisory-group--full.html.twig
- web/themes/custom/cloudy/templates/groups/bureau-office/group--bureau-office--full.html.twig
- web/themes/custom/cloudy/templates/groups/program/group--program--full.html.twig
- web/themes/custom/cloudy/templates/groups/project/group--project--full.html.twig
> POWR-2015 POWR-2014 POWR-2018 draggable views permission, parks facets, event status

- web/themes/custom/cloudy/templates/content/notification/node--notification--featured.html.twig
This PR fixes an issue where `field_notification_severity` was not being evaluated correctly to set the notification severity.
> POWR-2139 fix field_notification_severity not being passed to template correctly

- .circleci/config.yml
- .lando.yml
> POWR-2145: use lock file for node dependencies on circleCi

- web/sites/default/config/views.view.media.yml
Switches all media browsers to use a mini pager. This fixes the issue with the pager not resetting when using an exposed filter.
> POWR-1938 Fix filter issue with media browsers

- composer.json
- composer.lock
- web/modules/custom/portland/src/Logger/Processor/HostnameProcessor.php
- web/sites/default/config/core.extension.yml
- web/sites/default/config/dblog.settings.yml
- web/sites/default/config/lightning_core.versions.yml
- web/sites/default/monolog.services.yml
- web/sites/default/services.yml
- web/sites/default/settings.php
1. Sends logs to Loggly (in addition to standard dblog)
2. Truncate dblogs to 10,000 messages
> POWR-1403 Send logs to Loggly

- web/modules/custom/portland/templates/block--portland-legacy-paths-block.html.twig
- web/modules/custom/portland/templates/block--portland-revision-block.html.twig
- web/themes/custom/cloudy/src/components/message/message.scss
- web/themes/custom/cloudy/src/css/_components.scss
- web/themes/custom/cloudy/templates/block/block--views-block--back-reference-related-content-block-1.html.twig
- web/themes/custom/cloudy/templates/search/search-api-page.html.twig
- Updated message styling to reflect subtle color pairings from Figma and created separate stylesheet for messages, separate from alert styles
- Refactored classes on legacy paths, revisions, back-reference related content blocks, and search api (no results found) message
> POWR-2218 Fix message styling

- web/themes/custom/cloudy/src/components/_buttons.scss
- web/themes/custom/cloudy/src/components/alert/alert.scss
- web/themes/custom/cloudy/src/components/card/card.scss
- web/themes/custom/cloudy/src/css/core/_bootstrap-overrides.scss
- web/themes/custom/cloudy/src/css/core/_spacing.scss
- web/themes/custom/cloudy/src/design-tokens/color.js
- web/themes/custom/cloudy/src/design-tokens/spacing.js
- Decrease Alert vertical spacing
- Add background color to Tile to account for transparent images
- Update pagination styling
- Darken form submit button color
- Move spacing tokens into Style Dictionary
- Update Teal shades
> POWR-2212 Decrease Alert vertical spacing

- web/modules/custom/portland/modules/portland_edit_forms/back_reference_block.inc
- web/modules/custom/portland/src/Plugin/Block/RevisionBlock.php
- web/modules/custom/portland/templates/block--portland-legacy-paths-block.html.twig
- web/modules/custom/portland/templates/block--portland-revision-block.html.twig
- web/themes/custom/cloudy/src/components/_content.scss
- web/themes/custom/cloudy/src/components/message/message.scss
- web/themes/custom/cloudy/templates/block/block--views-block--back-reference-related-content-block-1.html.twig
- web/themes/custom/cloudy/templates/search/search-api-page.html.twig
- Update Legacy Path and Back Reference blocks to use default message style
- Update warning message icon
- Clean up message styling
- Add consistent border-radius across messages
> POWR-2224 Message styling updates

- composer.json
- composer.lock
- web/sites/default/config/config_split.config_split.config_local.yml
- web/sites/default/config/lightning_core.versions.yml
- web/sites/default/config/seckit.settings.yml
- web/sites/default/config_local/stage_file_proxy.settings.yml
Stage_file_proxy module is only enabled in the "local" config split. So main QA needs to happen on Lando environment.
> POWR-2186 Use stage_file_proxy for local dev access to prod files

- .circleci/config.yml
- tests/features/bootstrap/FeatureContext.php
* Check for login failure and retry up to 3 times
* Split tests by filename since timing data doesn't exist for Behat tests
* Fixed issue with invalid artifact filenames when test name contained characters not valid in filenames
> POWR-2199 Figure out CircleCI false failures

- web/sites/default/config/webform.webform.look_up_your_hauler.yml
- web/sites/default/config_local/webform.webform.website_feedback.yml
* Add placeholder example address
* Add help text
* Decrease input field size for better mobile display
> POWR-2264 Make garbage hauler lookup more user friendly

- web/sites/default/config/field.field.media.audio.field_display_groups.yml
- web/sites/default/config/field.field.media.chart.field_display_groups.yml
- web/sites/default/config/field.field.media.document.field_display_groups.yml
- web/sites/default/config/field.field.media.image.field_display_groups.yml
- web/sites/default/config/field.field.media.map.field_display_groups.yml
- web/sites/default/config/field.field.media.video.field_display_groups.yml
- web/sites/default/config/field.field.node.calendar_item.field_display_groups.yml
- web/sites/default/config/field.field.node.city_service.field_display_groups.yml
- web/sites/default/config/field.field.node.construction_project.field_display_groups.yml
- web/sites/default/config/field.field.node.development_permit.field_display_groups.yml
- web/sites/default/config/field.field.node.event.field_display_groups.yml
- web/sites/default/config/field.field.node.external_resource.field_display_groups.yml
- web/sites/default/config/field.field.node.news.field_display_groups.yml
- web/sites/default/config/field.field.node.notification.field_display_groups.yml
- web/sites/default/config/field.field.node.page.field_display_groups.yml
- web/sites/default/config/field.field.node.policy.field_display_groups.yml
- web/sites/default/config/field.field.node.service_location.field_display_groups.yml
- web/sites/default/config/views.view.content.yml
- web/sites/default/config/views.view.my_content.yml
* Changed Parent column label to "Owner"
* Added Also Offered By column to show display groups
* Used twig display logic to not repeat the Owner group in the Offered By list
* Updated all content types to use the Offered By label
> POWR-2374 added Offered By column to content views

- web/themes/custom/cloudy/src/components/card/card.scss
- web/themes/custom/cloudy/src/css/_pages.scss
- web/themes/custom/cloudy/templates/paragraphs/paragraph--card-deck.html.twig
Fixes Service card deck layout.
> POWR-2354 fix: service card deck layout

- web/themes/custom/cloudy/src/css/_typography.scss
- web/themes/custom/cloudy/src/design-tokens/typography.js
This pr fixes typography calculations when running `lando yarn start` or `lando yarn watch`.
> POWR-2447 Fix yarn watch on typography changes

- web/themes/custom/cloudy/src/components/_site-footer.scss
This PR provides consistency between the spacings of the footer menu items.
**To test:**
1. Navigate to https://powr-2466-portlandor.pantheonsite.io/
1. Turn your attention to the footer menu items —> Verify —> Menu item spacing is consistent
> POWR-2466: Footer contact spacing

- web/sites/default/config/field.field.group.bureau_office.field_featured_content.yml
- web/sites/default/config/field.field.group.elected_official.field_featured_content.yml
- web/sites/default/config/field.field.group.program.field_featured_content.yml
- web/sites/default/config/field.field.node.construction_project.field_body_content.yml
- web/sites/default/config/field.field.node.council_document.field_body_content.yml
- web/sites/default/config/field.field.node.development_permit.field_body_content.yml
- web/sites/default/config/field.field.node.event.field_body_content.yml
- web/sites/default/config/field.field.node.news.field_body_content.yml
- web/sites/default/config/field.field.node.page.field_body_content.yml
- web/sites/default/config/field.field.node.policy.field_body_content.yml
- web/sites/default/config/field.field.node.service_location.field_body_content.yml
Includes updates for both small stories.
POWR-2471 - removes Service Location from featured content types for Bureau/Office, Program, and Elected Official.
POWR-1620 -
> POWR-2471 and POWR-120

- web/themes/custom/cloudy/src/components/_site-footer.scss
- web/themes/custom/cloudy/src/css/_pages.scss
- web/themes/custom/cloudy/templates/layout/page.html.twig
This pr addresses the incocnistent spacing between footer elements.
> POWR-2519 Fix footer spacing between elements

- web/themes/custom/cloudy/src/components/_content.scss
- web/themes/custom/cloudy/templates/field/field--media--field-document.html.twig
- web/themes/custom/cloudy/templates/field/file-link.html.twig
This PR prevents document file size from wrapping to a new line when space exists to accomidate it inline with the file name.
> POWR-2498 Fix display of embedded documents

- web/sites/default/settings.php
This branch is part of a spike. Once successful file deletion can be confirmed, this PR and multidev can be deleted. This should occur around 4:30 PM on 9/24.
> POWR-2694 enabled file deletion

- web/modules/custom/portland/src/Plugin/Validation/Constraint/EventDateTimeConstraint.php
- web/themes/custom/cloudy/templates/content/events/node--event.html.twig
- Fix Event "All day" on default view mode
- Fix typo in event datetime constraint
> POWR-2771 fix 'All day' text display on default view mode

- web/apps/water/waterworks/css/main.css
- web/apps/water/waterworks/index.html
- web/apps/water/waterworks/js/waterworks_controllers.js
- web/apps/water/waterworks/site.webmanifest
- web/sites/default/config/views.view.waterworks_project_feed.yml
- Center project onscreen after list click
- Fix path to webmanifest for web app
- Increased data feed timeout from 5 to 7 seconds
> POWR-2929 WaterWorks app migration follow-ups

- .circleci/config.yml
Reverts eGovPDX/portlandor#1688
> Revert "POWR-3058 Delete all related multi-devs when a branch is merged"

- composer.json
- composer.lock
- web/modules/custom/portland/portland.module
- web/sites/default/config/core.extension.yml
- web/sites/default/config/lightning_core.versions.yml
- web/sites/default/config/views.view.alerts.yml
- web/sites/default/config/views.view.db_search_group_services_and_pages.yml
- web/sites/default/config/views.view.events_index.yml
- web/sites/default/config/views.view.group_notifications.yml
- web/sites/default/config/views.view.news_index.yml
- web/sites/default/config/views.view.park_finder.yml
- web/sites/default/config/views.view.search_charter_code_policies.yml
- web/sites/default/config/views.view.services_fullindex.yml
- web/sites/default/config/views.view.sitewide_child_groups_index.yml
- web/sites/default/config/views.view.sitewide_construction_projects.yml
Reverts eGovPDX/portlandor#1697
> Revert "POWR-3085 Enable View Custom Cache Tag for services and alerts"

- web/sites/default/config/views.view.admin_content_with_tables.yml
- Make title/content type sortable
- Add page type to content type field
- Add sortable/filterable Group field
- Add moderation state field
- Add sortable "Updated" field showing last modified date and user
> POWR-3173 Add more controls to admin "Content with tables" view

- web/sites/default/config/views.view.group_banner.yml
- web/sites/default/config/webform.webform.ada_accommodation_request.yml
- web/sites/default/config/webform.webform.website_feedback.yml
This PR will also serve as a deployment test, after recent incidents in Test and Live.
> POWR-3360 Update webform setting to support ZenDesk

- web/sites/default/config/views.view.change_sets.yml
- web/sites/default/config/views.view.construction_map.yml
- web/sites/default/config/views.view.council_agendas.yml
- web/sites/default/config/views.view.council_documents.yml
- web/sites/default/config/views.view.db_search_by_term.yml
- web/sites/default/config/views.view.db_search_group_construction.yml
- web/sites/default/config/views.view.db_search_group_events.yml
- web/sites/default/config/views.view.db_search_group_news.yml
- web/sites/default/config/views.view.db_search_group_policies.yml
- web/sites/default/config/views.view.db_search_group_projects.yml
- web/sites/default/config/views.view.db_search_group_services_and_pages.yml
- web/sites/default/config/views.view.events_index.yml
- web/sites/default/config/views.view.group_calendar_archive.yml
- web/sites/default/config/views.view.group_child_groups.yml
- web/sites/default/config/views.view.news_index.yml
- web/sites/default/config/views.view.park_finder.yml
- web/sites/default/config/views.view.portland_policies_search.yml
- web/sites/default/config/views.view.projects_index.yml
- web/sites/default/config/views.view.search_charter_code_policies.yml
- web/sites/default/config/views.view.search_group_documents.yml
- web/sites/default/config/views.view.services_fullindex.yml
- web/sites/default/config/views.view.sitewide_child_groups_index.yml
- web/sites/default/config/views.view.sitewide_construction_projects.yml
- web/sites/default/config/views.view.sitewide_groups_index.yml
- web/sites/default/config/views.view.taxonomy_content_by_term.yml
- web/themes/custom/cloudy/src/css/_overrides.scss
A really simple fix via a small CSS change pattered after how Claro's pagination wraps at smaller screen widths.
> POWR-3301 Fix mobile pagination

- .lando.yml
- web/sites/default/config/block.block.chartercodepoliciesbytype.yml
- web/sites/default/config/core.entity_form_display.media.audio.default.yml
- web/sites/default/config/facets.facet.charter_code_policies_by_type.yml
Merging this one to master to allow for deployment of recently merged sprint 60 release 1.
> POWR-3313 add filter by type to charter code policy search

- .lando.yml
- web/sites/default/config/group.role.advisory_group-dd56f9fc5.yml
- web/sites/default/config/group.role.bureau_office-dd56f9fc5.yml
- web/sites/default/config/group.role.elected_official-dd56f9fc5.yml
- web/sites/default/config/group.role.program-dd56f9fc5.yml
- web/sites/default/config/group.role.project-dd56f9fc5.yml
- web/sites/default/config/system.action.user_add_role_action.neighborhood_editor.yml
- web/sites/default/config/system.action.user_remove_role_action.neighborhood_editor.yml
- web/sites/default/config/user.role.administrator.yml
- web/sites/default/config/user.role.neighborhood_editor.yml
- web/sites/default/config/user.role.sitewide_editor.yml
- web/sites/default/config/views.view.admin_neighborhoods.yml
Also includes an enhancement for my code that disables Drupal modules before they're removed.
> POWR-3550 Manage neighborhoods view

- .lando.yml
Install theme dependencies as part of lando refresh command.
> POWR-4027 Add theme dependency updates to landofile

- web/sites/default/config/portland_zendesk.adminsettings.yml
- web/sites/default/config/webform.webform.zendesk_api_test.yml
Also created webform for testing API connectivity.
> CSM-144 updated Portland Zendesk config to use service account

- web/sites/default/config/webform.webform.request_ada_accommodation.yml
* Assign tickets to new ADA Accommodation Request assignment group in Zendesk
* Remove empty markup field in form
> CSM-167 ADA Accommodation Request form follow-ups

- web/sites/default/config/webform.webform_options.action_taken.yml
- web/sites/default/config/webform.webform_options.contact_type.yml
- web/sites/default/config/webform.webform_options.ticket_type.yml
These are for use in the Agent Use Only blocks on webforms.
> CSM-174 added new option sets

- web/sites/default/config/webform.webform.report_e_scooter.yml
- web/sites/default/config/webform.webform.report_e_scooter_resolution.yml
* Added new option to resolution form
* Added additional email address for spin
* Added new handler for cases where scooter company is not specified by community member; sends to all companies with special verbiage.
> CSM-179 E-scooter webform follow-ups

- web/sites/default/config/webform.webform.report_e_scooter.yml
Reconfigured API handlers to store lat/lon values in new individual fields in Zendesk, instead of the combined field.
> CSM-182 API handler update to Report an E-scooter webform

- web/sites/default/config/webform.webform.contact_elected.yml
Had to enable prepopulate on 2 fields.
> CSM-202 Enable deep linking to contact specific elected officials

- web/sites/default/config/views.view.sitewide_child_groups_index.yml
"No results" page shows "No Advisory Bodies" for other content type displays
> POWR-4232 Fix "no results" text on child groups index

- web/sites/default/config/webform.webform.report_campsite_or_vehicle.yml
* Changed some verbiage, "In addition to submitting this form" instead of "In addition to submitting this campsite report."
* Disabled abandoned autos routing
* Added Next Steps box for calling abandoned autos
* Misc logic tweaks, fixes
> CS-123 Additional updates to Campsite and Abandoned Autos form

- composer.lock
- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/src/Validate/GeolocationValidationConstraint.php
There was a mismatch between "lon" and "lng" in variable names.
> PGOV-721 fixed location widget bug

- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/portland_location_picker.module
- web/modules/custom/portland/modules/portland_location_picker/src/Element/PortlandLocationPicker.php
- web/sites/default/config/language/vi/views.view.page_menu.yml
- web/sites/default/config/language/zh-hans/views.view.page_menu.yml
- web/sites/default/config/webform.webform.3_1_1_regional_testing.yml
- web/sites/default/config/webform.webform._template_standard_webform.yml
- web/sites/default/config/webform.webform.location_widget_test_asset_map_s.yml
- web/sites/default/config/webform.webform.location_widget_test_asset_selec.yml
- web/sites/default/config/webform.webform.location_widget_test_capture_reg.yml
- web/sites/default/config/webform.webform.location_widget_test_open_reques.yml
- web/sites/default/config/webform.webform.report_camp_removal_complaint.yml
- web/sites/default/config/webform.webform.report_campsite_or_vehicle.yml
- web/sites/default/config/webform.webform.report_discrimination.yml
- web/sites/default/config/webform.webform.report_e_scooter.yml
- web/sites/default/config/webform.webform.report_graffiti.yml
- web/sites/default/config/webform.webform.report_graffiti_resolution.yml
- web/sites/default/config/webform.webform.report_trash_can.yml
- web/sites/default/config/webform.webform.request_ada_accommodation.yml
Had to remove the hard-coded required field validation from the widget and reconfigure all the webforms to require the field through config. Using this built-in method bypasses required field validation if the widget is hidden by conditional logic.
> CS-315 fixed validation error in ADA Accommodation request form

- web/sites/default/config/views.view.zendesk_tickets.yml
- web/sites/default/config/webform.webform.report_trash_can.yml
* Save reports to the Trash Can reporting group in Zendesk
* Update Zendesk tickets view query to not require the OK for Public flag in order to display tickets
> CS-309 final tweaks to trash cans report form

- web/sites/default/config/webform.webform._template_standard_webform.yml
- web/sites/default/config/webform.webform.report_camp_removal_complaint.yml
- web/sites/default/config/webform.webform.report_campsite_or_vehicle.yml
- web/sites/default/config/webform.webform.report_e_scooter.yml
- web/sites/default/config/webform.webform.report_graffiti.yml
- web/sites/default/config/webform.webform.report_graffiti_resolution.yml
- web/sites/default/config/webform.webform.report_trash_can.yml
https://www.drupal.org/project/clamav/issues/3058018
> CS-352 Revert CS-312 because of timeout issue

- web/modules/custom/portland/modules/portland_location_picker/README.md
- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/src/Element/PortlandLocationPicker.php
- web/modules/custom/portland/modules/portland_location_picker/src/Plugin/WebformElement/PortlandLocationPicker.php
- web/sites/default/config/webform.webform.location_widget_test_asset_map_s.yml
- web/sites/default/config/webform.webform.report_e_scooter.yml
* Enabled display_city_limits and require_city_limits properties and validation
* Changed some hidden fields to textfields with "visually-hidden" class (id attributes don't render on hidden fields for some reason)
> CS-454 add city limits geofencing to location widget

- .github/workflows/rebase-sandbox-with-master.yml
- pantheon.yml
- web/private/scripts/rebase_sandbox.php
The `secrets.json` file has been updated on Dev, Test, and Live with the new GitHub Actions personal access token.
> PGOV-985 Use deployments to trigger Sandbox rebase

- web/modules/custom/portland/modules/portland_location_picker/README.md
- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/src/Element/PortlandLocationPicker.php
- web/modules/custom/portland/modules/portland_location_picker/src/Plugin/WebformElement/PortlandLocationPicker.php
- web/modules/custom/portland/modules/portland_zendesk/portland_zendesk.info.yml
- web/sites/default/config/webform.webform.apply_tsup.yml
- web/sites/default/config/webform.webform.location_widget_test_capture_reg.yml
- web/sites/default/config/webform.webform.report_campsite_or_vehicle.yml
- web/sites/default/config/webform.webform.report_graffiti.yml
- web/sites/default/config/webform.webform.report_graffiti_resolution.yml
* Graffiti form updates
* Added RegionHidden option to location widget so that TSUP parking regions are hidden
* Changed how geofencing is performed; now uses PortlandMaps API call instead of static polygons; added additional custom property for checking city boundaries plus parks boundaries.
> CS-585 Graffiti updates + location widget update

- web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
* Remove Zendesk ticket handler condition that prevents a ticket being created if Community Garden
> SIT-940 Park Maintenance form 1.1 updates

- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/portland_location_picker.libraries.yml
- web/sites/default/config/webform.webform.report_campsite.yml
* Prepopulate email address on "submit another" link
* Add nicely formatted form input to confirmation email
> SIT-955 - Report a Campsite form 2.1 updates

- web/sites/default/config/webform.webform.engage_transition_team.yml
* Additional fields for comment/question/feedback track
* Added public records statement
* Connected comment/question/feedback track to Smartsheet
> SIT-941 Transition Team form 1.1

- web/sites/default/config/webform.webform.request_outreach_assistance.yml
* Added public records disclaimer text
> SIT-964 city outreach form 1.1

- web/sites/default/config/webform.webform.report_tnc_issue.yml
- web/sites/default/config/webform.webform.report_tnc_issue_update.yml
* TNC form
* TNC Update form
* Updated uncategorized webforms to have a category
> SIT-899 Rideshare/TNC report and update form

- web/sites/default/config/webform.webform.apply_dbi_credit.yml
* Added subzones and alphabetized
* Changed date and duration on confirmation page and in notification email
> SIT-993 DBI Credit application form updates

- web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
Changed conditional logic on submit section. Bad logic was preventing form submission if community center or garden.
> SIT-1044 Park Maintenance form bug fix

- web/sites/default/config/webform.webform.report_camp_removal_complaint.yml
Also added some computed twig elements to parse and format values before sending to the Smartsheet API.
> SIT-1050 Add Smartsheet handler to webform

- web/sites/default/config/webform.webform.report_graffiti.yml
- web/sites/default/config/webform.webform.report_graffiti_resolution.yml
* Add Signs & Streetlights question to primary form
** Handler to create MO Graffiti tickets and set Zendesk custom SSL field
** Omit SSL question from JSON
* Add full resolution URL as private note
* Add digitial_waiver_received tag if user signs off on waiver
* Add pgr_non_contract tag if no existing ticket ID and resolved by PGR
* Misc tweaks and fixes
> SIT-798 Report Graffiti form 2.0 updates

- .circleci/config.yml
- web/sites/default/config/webform.webform.request_ada_accommodation.yml
* Fix email link
* Add "Make selection to continue" text
> SIT-1081 ADA Accommodation Request form - fix email link

- web/sites/default/config/webform.webform.apply_tsup.yml
> SIT-1079 TSUP Form v1.2

- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/modules/custom/portland/modules/portland_location_picker/src/Plugin/WebformElement/PortlandLocationPicker.php
- web/sites/default/config/webform.webform.report_graffiti_resolution.yml
* Re-work the output of the location widget in the computed description field
* Trim the whitespace character off address details coming from the Intersects API
* Set resolution contractor consistently in the handlers, so it never appears in the JSON
* Fix a couple copy/paste errors in Location widget plug-in
> SIT-1078 - Report Graffiti | Form 2.1 updates

- web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
- web/sites/default/config/webform.webform.report_parks_issue.yml
- web/themes/custom/cloudy/templates/field/file-link.html.twig
* Safety form: add park zone to ticket subject line
* Update Tree Hazards next steps phone number
* Add "Feedback about staff encounter" issue type
* Disable uploaded image preview link for anonymous users (check file URL in template and only show link if image path does not start with /system/files/webform)
> SIT-1075 Park Safety 1.3 and Park Maint 1.2 form updates

- web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js
- web/sites/default/config/language/es/webform.webform_options.ethnicity.yml
- web/sites/default/config/webform.webform.apply_cooling_unit.yml
- web/sites/default/config/webform.webform.bds_demographic_survey.yml
* Change sender address to noreply@portlandoregon.gov and add "do not reply" message to confirmation.
> SIT-1110 Cooling Portland | Form 1.2

- web/sites/default/config/webform.webform.report_park_issue_resolution.yml
- web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
* Updated source URL and property name for park regions in location picker
* Update resolution form to set work order number in zendesk ticket
> SIT-1122 Park Maintenance | Form 1.4 updates

- web/sites/default/config/webform.webform.apply_cooling_unit.yml
* Add more help text to address field
* Update confirmation message
* Change "Family member over 60..." to "Household member..."
> SIT-1123 Cooling Portland | Form 1.3

- web/sites/default/config/webform.webform.apply_portland_sign.yml
Add use of Ajax and reword confirmation page.
> SIT-1159 Update Portland sign webform

- web/sites/default/config/webform.webform.file_delivery_fee_complaint.yml
* Updated phone number in confirmation email
* Removed the article "a" so that it sorts better in the admin webforms list
> SIT-1167 Minor changes to Delivery Fee Complaint form

- web/modules/custom/portland/modules/portland_legacy_redirects/src/Field/RedirectList.php
Refactored redirect creation/deletion to respect current language. Additionally, only create/delete redirects when they've actually changed.
> PGOV-1193 Fix legacy path disappearing after editing a translated version

- web/sites/default/config/webform.webform.apply_tsup.yml
Fix typo, remove non-refundable lang on parking reservation permit
> SIT-1189 TSUP | Form 1.5

- web/sites/default/config/webform.webform.report_e_scooter.yml
- web/sites/default/config/webform.webform.report_e_scooter_resolution.yml
Updated the resolution form to include Lyft.
Removed the old "update interaction ticket" handler that's not in use, and hid unused fields in Customer Service Use Only block.
> SIT-1200 Report an E-Scooter | Form 2.2

- web/sites/default/config/webform.webform.request_ada_accommodation.yml
- web/sites/default/config/webform.webform.request_language_services.yml
- web/sites/default/config/webform.webform.request_language_services_gen.yml
- web/sites/default/config/webform.webform.request_language_services_parks.yml
- web/sites/default/config/webform.webform_options.languages_ppr.yml
Includes
* Updates to the ADA form
* 2 forms from SIT-1208, a parks and a generic version of the language request form
* A new webform options list of languages
> SIT-1206 - Request A.D.A Accommodation | Form 1.1

- web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
- web/sites/default/config/webform.webform.report_towing_complaint.yml
Also includes updated email recipient small conditional logic change on park maintenance form routing for community gardens.
> SIT-1235 | Towing Complaints | Form 1.2

- .lando.yml
- web/modules/custom/portland/portland.links.action.yml
- web/sites/default/config/views.view.top_searches.yml
Also renamed the menu option and URL to use consistent naming of "popular searches". And changed domain name of Lando solar service to be unique to the project.
> PGOV-1223 Popular search admin view limited to 10 items

- web/modules/custom/portland/modules/portland_smartsheet/src/Plugin/WebformHandler/SmartsheetHandler.php
- web/sites/default/config/webform.webform.apply_cooling_unit.yml
- web/sites/default/config/webform.webform.bds_demographic_survey.yml
- web/sites/default/config/webform.webform.bes_stormwater_intake.yml
- web/sites/default/config/webform.webform.file_delivery_fee_complaint.yml
- web/sites/default/config/webform.webform.report_demographics.yml
- web/sites/default/config/webform.webform.request_lead_test_kit.yml
- web/sites/default/config/webform.webform.request_permit_extension.yml
- web/sites/default/config/webform.webform.request_records_information.yml
Submission ID key contained a __ which after a recent change, made it get detected as a composite element
> SIT-1250 fix submission ID not making it to Smartsheet

- tests/percy/__full_tests__/full_admin.js
- web/modules/custom/portland/modules/portland_groups/portland_groups.module
QA results from running tests on my local:
> PGOV-1103 Fix full regression tests

- web/modules/custom/portland/modules/portland_zendesk/src/Plugin/WebformHandler/ZendeskHandler.php
> SIT-1280 Fix bug in Zendesk handler

- web/sites/default/config/views.view.page_menu.yml
> PGOV-1361 fix page menu showing for anonymous users when parent is unpublished

- composer.json
- patches/3413647-entity-embed-html-in-captions.patch
- web/themes/custom/cloudy/src/css/drupal/_ckeditor-accordion.scss
> PGOV-1383 Fix vertical accordion spillover and HTML tags showing in caption

- web/modules/custom/portland/modules/portland_ecouncil/portland_ecouncil.links.menu.yml
- web/sites/default/config/views.view.council_absences.yml
- web/sites/default/config/views.view.manage_council_documents.yml
Also fix council absences menu not appearing when no view results
> PGOV-1395 Replace "Upcoming" tab with "Add Document" for council authors

- web/sites/default/config/webform.webform.report_abandoned_vehicle.yml
- web/sites/default/config/webform.webform_options.vehicle_color.yml
Urgent conditional logic fix related to recent change to checkbox values
> SIT-1319 | Transportation Wallet form 1.6

- web/sites/default/config/webform.webform.contact_elected_official_2025.yml
A couple of small form tweaks. The biggest change is that tickets are now created using the Zendesk handler, not the email handler.
> PGOV-1418 Contact and Elected Official form v2.4

- web/modules/custom/portland/portland.views.inc
- web/modules/custom/portland/src/Plugin/views/field/NodeEditoria11yResults.php
- web/sites/default/config/views.view.my_content.yml
> PGOV-1412 add views plugin to show editoria11y results count in My Content

- web/sites/default/config/webform.webform.3_1_1_regional_testing.yml
- web/sites/default/config/webform.webform.report_demographics.yml
- web/sites/default/config/webform.webform.report_e_scooter.yml
- web/sites/default/config/webform.webform.report_e_scooter_resolution.yml
- web/sites/default/config/webform.webform.report_noise_concern.yml
- web/sites/default/config/webform.webform.report_row_obstruction.yml
SITU-1105: Add help text to name field
SITU-1079: Update 311 Regional Testing form to use Zendesk handler
SITU-1084: Report an E-Scooter form updates
SITU-1109: Remove gender identity question from Demographics form
SITU-1080: Enable city limits geofencing on ROW Obstruction form
> SITU-1105 Minor form updates

- web/sites/default/config/mailsystem.settings.yml
- web/themes/custom/cloudy/webpack.config.js
> PGOV-1482 Enable password reset emails

- web/sites/default/config/webform.webform.transportation_wallet.yml
Fixed conditional logic around which date element to use for date of birth, depending on whether the selected hop card required 65+.
Fixed some computed twig elements that weren't handling dates correctly.
> SITU-1151 Transportation Wallet form - fixed conditional logic around birth dates

- web/sites/default/config/webform.webform.contact_elected_official_2025.yml
- web/sites/default/config/webform.webform.report_cable_complaint.yml
- web/sites/default/config/webform.webform.report_happening_on_my_street.yml
- web/sites/default/config/webform.webform_options.feedback_topics.yml
Also includes the new What's Happening On My Street form that Josh built. I've updated it with our naming conventions and smoke tested it.
> SITU-1205 Contact an Elected Official form updates
