eGovPDX/portlandor

web/sites/default/config/block.block.communityactions.yml, web/sites/default/config/core.extension.yml, web/sites/default/config/lightning_core.versions.yml, web/sites/default/config/page_manager.page.frontpage.yml, web/sites/default/config/page_manager.page.node_view.yml, web/sites/default/config/page_manager.page_variant.frontpage-panels_variant-0.yml, web/sites/default/config/views.view.community_actions.yml, web/sites/default/config/views.view.frontpage.yml
Please note, I went ahead and added Pages and the Page Manager UI to this feature so that I could create a homepage that could have blocks placed on it. We can use Page manager for content type or path specific layouts as we go forward. I'll demo this with the team next week.
=> POWR-59 Add community actions block to homepage.

web/sites/default/config/chosen.settings.yml
I've modified the Chosen config to only target three specific fields: 
- select#edit-field-topics
- select#edit-field-audience
- select#edit-field-community-actions
Contrary to Mike's comments in the meeting today, it's not possible to otherwise turn Chosen off using other config options. You can turn it ON for all controls, but not turn it OFF for all. Specifying the controls it targets seems to be the sole way this is done.
=> POWR-164 Configure Chosen to only target specific fields

README.md
I think this change to instructions is really all we can/should do to address the composer failures due to rate limiting.
=> POWR-169 update the project README.md with Github OAuth instructions.

web/modules/custom/portland/portland.module, web/sites/default/config/field.field.group.bureau_office.field_shortname_or_acronym.yml, web/sites/default/config/field.field.group.program.field_shortname_or_acronym.yml, web/sites/default/config/pathauto.pattern.group_title.yml
The majority of functionality for this story is in the portland.module file, which has two hooks to capture the group create and update events. That is where the URL aliases are created/updated. Config updates include: field description updates and some pathauto pattern updates.
=> POWR-142 Expand pathauto options for group content list pages

web/themes/custom/cloudy/cloudy.theme
When loading a past revision, the $node var is a string representation of the node id, but the following loadByEntity($node) function expects an object of type ContentEntityInterface. I added logic to check the type, and reload $node as a node object if it's not the right type.
=> POWR-450 - Fix for broken node revisions

web/themes/custom/cloudy/js/global.js, web/themes/custom/cloudy/templates/field/field--field-service-mode.html.twig
This is in QA and ready for review as soon as it passes testing.
The diff of global.js is showing some code updates that are unrelated to this story. The existing code was improperly indented, so I fixed it but did not materially change that code.
My new accessibility and URL fragment handling code is in global.js in the section Drupal.behaviors.tab_handler. The code does the following:
* Put fragment in URL
* Use URL fragment to activate specified tab on page reload or direct navigation
* Set tabindex = -1 for all non-active tabs
* Set aria-hidden = true for all non-visible panes
* Focus active tab, for when user reloads or arrives via direct navigation
* Enable left/right arrow key navigation on tabs
In field--field-service-mode.html.twig, I added a number of attributes to the tabs and …
=> POWR-323 - updates to tabs for accessibility

web/modules/custom/portland/templates/portland-alert.html.twig, web/sites/default/config/views.view.bureaus_and_offices.yml, web/sites/default/config/views.view.services_index.yml, web/themes/custom/cloudy/cloudy.theme, web/themes/custom/cloudy/templates/block/block--system-menu-block.html.twig, web/themes/custom/cloudy/templates/field/field--paragraph--field-step-title.html.twig, web/themes/custom/cloudy/templates/layout/html.html.twig, web/themes/custom/cloudy/templates/layout/page.html.twig, web/themes/custom/cloudy/templates/navigation/pager.html.twig
This branch and PR includes a number of very small updates. I'v aggregated them into a single branch to prevent all the overhead of multiple branches/PRs. These are all sub-stories of POWR-545.
POWR-551 Add role="banner" to site header
POWR-552 Remove/hide empty tabs region
POWR-553 Remove duplicate nav element from main navigation
POWR-554 Pager nav needs role and aria-labelledby
POWR-557 Service step headings should be h2
POWR-548 Homepage search add role and update label
POWR-556 Services page search input needs label
POWR-555 Update skip link to point to #main and remove old anchor
POWR-580 Move alerts to above "skip to main content" link for accessibilty
I've unit tested these all in the powr-545 multidev, and code is rebased as of 11/29 at 1:00 pm.
=> POWR 545 - Stories that stem from user testing and WAVE tool analysis

web/themes/custom/cloudy/templates/views/views-view-table--media.html.twig
Lightning Media allows only a single media item to be selected through the use of the data-selectable attribute. However, the Lightning implementation only supports grid views. I've added a template that adds the attribute to rows in all table displays in the Media view. This resolves the issue of being able to select multiple bulk-select checkboxes. The checkboxes are still visible, but only one can be checked at a time now. It didn't make sense to hide the checkboxes, like Lightning does when displaying a grid of thumbnails, because there is no obvious place to click like the thumbnail.
=> POWR-645 - Media browsers updated to only allow single item selection

web/themes/custom/cloudy/templates/field/field--field-service-mode.html.twig
The service mode template has been updated to use the service mode names as the fragment identifiers. I've replaced spaces with hyphens and lowercased the names.
=> POWR-744 - make service tab fragment identifier descriptive

web/modules/custom/portland/modules/portland_media_embed_helper/src/Plugin/Filter/PortlandMediaEmbedHtmlFilter.php, web/sites/default/config/filter.format.simple_editor.yml
This is the first part of the merge. It includes the new filter codefile, and removes HTML Purifier from all the text editors in preparation for module uninstall (uninstall occurs in 2nd part of merge)
=> POWR-785-0 - Replace HTML Purifier (MERGE 1st)

web/modules/custom/portland/modules/portland_media_embed_helper/src/Plugin/Filter/PortlandMediaEmbedHtmlFilter.php, web/sites/default/config/filter.format.simple_editor.yml
This is the 2nd part of the merge, which enables the new text format filter, and uninstalls HTML Purifier and removes it from composer.json. This PR will not rebuild correctly in multidev without first having POWR-785-0 deployed to the environment.
=> POWR-785-1 - Replace HTML Purifier (MERGE 2nd)

web/modules/custom/portland/modules/portland_legacy_redirects/src/Plugin/Validation/Constraint/RelativePathConstraintValidator.php, web/themes/custom/cloudy/scss/components/_form.scss
The real issue is that the detailed error message wasn't being displayed due to a CSS issue. That has been corrected. I've also enabled the duplicate path error message to include a link to the page that contains the duplicate.
=> POWR-775 - Legacy path error

web/sites/default/config/search_api.index.full_index.yml
This should fix the search error that occurred after pushing the changes from 821 (remove Guide and Information content types)
=> POWR-821-1 Remove body_content field from search config

.circleci/config.yml, composer.json, tests/features/bootstrap/FeatureContext.php, web/private/scripts/circleci_webhook.php, web/private/scripts/drush_post_deploy_cache_rebuild.php, web/private/scripts/drush_post_deploy_config_import.php, web/private/scripts/drush_post_deploy_cron.php, web/private/scripts/drush_post_deploy_updatedb.php
**Key changes:**
* Dependabot PRs use the following naming convention for multidev sites: bot-### where ### is the PR number.
* Dependabot branches are renamed to bot-### when pushed to Github
* At the end of the deploy job for Dependabot branches, it pauses for 3 minutes then directly triggers the test job. (The Pantheon webhook tries to trigger the test job with the wrong branch name so it doesn't get run twice.)
https://github.com/eGovPDX/portlandor/pull/716 is an example of a Dependabot PR based off of this branch which has successfully passed both CI jobs.
=> POWR-1129 Update CircleCI for Dependabot

web/modules/custom/portland/src/Plugin/Action/ArchiveAction.php, web/modules/custom/portland/src/Plugin/Action/MarkForReviewAction.php, web/modules/custom/portland/src/Plugin/Action/PublishAction.php, web/sites/default/config/views.view.group_nodes.yml, web/sites/default/config/views.view.my_content.yml
Previously, the bulk actions did not record who made the action outside of the revision log. This is problematic for seeing who bulk unpublished or published content.
Addtionally, the bulk action to Mark for Review is not triggering the reviewer field to be built for either the group content or my content views. I temporarily removed that feature as there is not a quick fix to making that form build that I can see. It works fine on the sitewide admin content view, so I left the feature in place at that level to troubleshoot in a future story.
=> POWR-1498 update bulk actions to include revision user

tests/features/bootstrap/FeatureContext.php
I noticed that the majority of the recent "fake" build failures happened right after the waitForThePageToBeLoaded() function/test which had a timeout of 10s. I suspect our failures are caused by intermittent uncached page loads exceeding 10s. So I've bumped the timeout up to 20s hoping that resolves the issue.
=> POWR-1438 Address intermittent build error

web/themes/custom/cloudy/scss/_overrides.scss, web/themes/custom/cloudy/templates/block/block.html.twig
I removed the copyright footer image from the background, and replaced it with an image tag that renders after the content if it's plugin-id contains the substring 'copyright'.
=> POWR-1478 Convert city seal in footer from a background image to an inline image

web/sites/default/config/core.entity_form_display.group.advisory_group.default.yml, web/sites/default/config/core.entity_form_display.group.bureau_office.default.yml, web/sites/default/config/core.entity_form_display.group.elected_official.default.yml, web/sites/default/config/core.entity_form_display.group.program.default.yml, web/sites/default/config/core.entity_form_display.group.project.default.yml, web/sites/default/config/core.entity_view_display.group.advisory_group.default.yml, web/sites/default/config/core.entity_view_display.group.bureau_office.default.yml, web/sites/default/config/core.entity_view_display.group.program.default.yml, web/sites/default/config/core.entity_view_display.group.project.default.yml, web/sites/default/config/field.field.group.advisory_group.field_address.yml, web/sites/default/config/field.field.group.bureau_office.field_address.yml, web/sites/default/config/field.field.group.bureau_office.field_facebook.yml, web/sites/default/config/field.field.group.bureau_office.field_instagram.yml, web/sites/default/config/field.field.group.bureau_office.field_twitter.yml, web/sites/default/config/field.field.group.elected_official.field_address.yml, web/sites/default/config/field.field.group.program.field_address.yml, web/sites/default/config/field.field.group.program.field_facebook.yml, web/sites/default/config/field.field.group.program.field_instagram.yml, web/sites/default/config/field.field.group.program.field_twitter.yml, web/sites/default/config/field.field.group.project.field_address.yml
* Enabled display of contact info fields on all types except Elected Official (it was already enabled there)
* Made fields consistent across group types
** Set United States as country
** Changed Address label to Mailing address and removed useless help text
* Added social media fields to Bureau/Office and Program
=> POWR-1535 Display contact information on all group types

web/sites/default/config/core.entity_view_display.node.city_service.teaser.yml, web/themes/custom/cloudy/scss/components/_badge.scss, web/themes/custom/cloudy/templates/field/field--field-popular.html.twig
This adds the services badge to the teaser display for services. It also adds new style to the popular badge style so when the two badges stand next to each other they are distinct from each other and that they also don't look "clickable".
=> POWR-1543 Add badge to services in /group/services

web/themes/custom/cloudy/scss/_overrides.scss, web/themes/custom/cloudy/scss/components/_dialog.scss, web/themes/custom/cloudy/scss/components/_form.scss, web/themes/custom/cloudy/scss/components/_list-group.scss, web/themes/custom/cloudy/scss/components/_nav.scss, web/themes/custom/cloudy/scss/components/_paragraphs.scss, web/themes/custom/cloudy/scss/components/_site-footer.scss
Removing redundant style overrides or moving them to component scss files.
Files affected:
- _dialog
- _forms
- _list-group
- _nav
- _paragraphs
- _site-footer
To Test-
- Go to https://powr-1556-portlandor.pantheonsite.io/.
Check the homepage, services main page, bureaus and offices main page, and alerts main page at different breakpoints to ensure there is no style regression.
=> POWR-1556 _Overrides Audit

.circleci/config.yml
This will fix the [deploy failing here](https://circleci.com/gh/eGovPDX/portlandor/8782?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) by giving more time for the deploy to complete (10 minutes => 15 minutes).
=> ci: increase deploy timeout allowed

web/modules/custom/portland/modules/portland_groups/portland_groups.module, web/sites/default/config/core.entity_form_display.media.audio.media_browser.yml, web/sites/default/config/core.entity_form_display.media.document.media_browser.yml, web/sites/default/config/core.entity_form_display.media.image.media_browser.yml, web/sites/default/config/core.entity_form_display.media.map.media_browser.yml, web/sites/default/config/core.entity_form_display.media.video.media_browser.yml, web/sites/default/config/entity_browser.browser.audio_video_browser_embed.yml, web/sites/default/config/entity_browser.browser.document_browser.yml, web/sites/default/config/entity_browser.browser.document_browser_embed.yml, web/sites/default/config/entity_browser.browser.featured_image.yml, web/sites/default/config/entity_browser.browser.image_browser_embed.yml, web/sites/default/config/entity_browser.browser.map_browser_embed.yml, web/sites/default/config/entity_browser.browser.media_browser.yml, web/sites/default/config/entity_browser.browser.video_browser.yml, web/sites/default/config/views.view.media.yml
* Implements hook_entity_insert to manually add a new media entity to a group if it is created in the context of an inline entity form. Works with all media types.
* Reverts temporary changes to entity browsers as workaround while bug was fixed.
=> POWR-1750 - Media losing group content relationship when created inline

web/sites/default/config/core.entity_view_display.group.program.search_result.yml
This is a hotfix for the heading level of "program" search results. This patches the DS module approach with the correct configuration. PR POWR-1795 and its follow up integration with Drupal should provide a long term correction in which all search result cards will use the same template, removing the possibility of configuration drift between the rendering of various content type search results.
=> POWR-1796: Hotfix Search Result "Program" heading level to h2

web/themes/custom/cloudy/src/components/_search.scss
On both the homepage search bar and header search bar, the css was declaring an explicit height of the inner white text input area, instead of allowing the input area to fill the space. On the homepage, this was causing a rounding error with pixels (the inner text area was 68.78px, which on some hi rescreens would add a line of blue pixels).
Testing:
1. Go to the https://powr-1909-portlandor.pantheonsite.io/
2. Make sure the homepage search bar looks correct (no blue line above or below the text input) across all screen widths (this is best tested on a hi res screen)
3. Go to a page that includes the search bar in the header. The search bar input area should be the same height and flush with the magnifier glass icon.
4. Check other instances of the search bar, such as …
=> POWR-1909 Search Bar Height

web/themes/custom/cloudy/src/components/_header.scss, web/themes/custom/cloudy/templates/layout/page.html.twig
Fixes the nesting of container/layout element in the header so header content respects the same step-wise container behavior as main content (the header content has the same left/right alignment as the rest of the page). This should be addressed across all breakpoints. See the below "After" image for a sense how this should look.
Testing:
1) Go to https://powr-1904-portlandor.pantheonsite.io/
2) Test across all browser widths that the left-hand edge of the header logo aligns with the left-hand edge of the content. See below for guidance
=> POWR-1904 header navbar container alignment

web/themes/custom/cloudy/templates/field/file-link.html.twig
This broke after some work that Mike did with document icons. All I had to do was add an additional default filter with the file description.
=> POWR-1723 Related document description not being used as link text

web/themes/custom/cloudy/pattern-lab/_patterns/01-components/breadcrumb/05-main-demo.twig, web/themes/custom/cloudy/pattern-lab/_patterns/01-components/breadcrumb/10-type-variations.twig, web/themes/custom/cloudy/src/components/breadcrumb/breadcrumb.scss, web/themes/custom/cloudy/src/components/breadcrumb/breadcrumb.twig
POWR-1902 - Screen readers were picking up the "/" inbetween breadcrumb items. As there is not a way to hide psuedo-elements from screen readers, the "/" was turned into a span with aria-hidden. No visual changes to the breadcrumbs, but screen readers will no longer read out the "/".
POWR-1906 - Cleaned up the breadcrumb PL docs, including better content and an example of a really really long breadcrumb.
Testing POWR-1902:
1) Go to https://powr-1902-portlandor.pantheonsite.io/, then to any other page on the site
2) Use a screen reader to navigate to the breadcrumbs
3) The screen reader should read each crumb, but not the "slash" between them.
Testing POWR-1906:
1) Go to https://powr-1902-portlandor.pantheonsite.io//pattern-lab/patterns/01-components-breadcrumb/index.html
2) See the …
=> POWR-1902 POWR-1906 Breadcrumb Screen Reader Improvements, PL Docs

web/themes/custom/cloudy/src/css/core/_bootstrap-overrides.scss
Previous behaviour: All grid gutters were 30px wide.
New behaviour: Grid gutters track spacing responsiveness... on small screens the gutter is 28px (2 * 14px), on medium screens 32px (2 * 16px), and on large screens 36px (2 * 18px).
=> POWR-1963 feat: better grid gutters

web/themes/custom/cloudy/src/layouts/group-default/group-default.twig
Previously the lead paragraph on group default layout was always in a 50% grid column on large screens, even if no featured image was present. Now the lead paragraph is in a full width column if no featured media is present.
=> POWR-1948 LAYOUT: Group lead paragraph should not be 50% width

web/themes/custom/cloudy/package.json, web/themes/custom/cloudy/src/components/_form.scss, web/themes/custom/cloudy/src/components/breadcrumb/breadcrumb.scss, web/themes/custom/cloudy/src/css/_overrides.scss, web/themes/custom/cloudy/templates/layout/page.html.twig, web/themes/custom/cloudy/templates/layout/region--pre_content.html.twig
Updates _overrides.scss to hide the following regions and blocks from print:
.region-global-admin
.region-pre-header
.region-primary-menu
.region-tabs
.block-portland-revision-block
.portland-revision--block
.block-fixed-block-contentfooter-links
.block-views-blockback-reference-related-content-block-1
#block-feedbacklink
Updates the _form.scss to remove a deprecated element that keeps erroring the build.
Adds a width to .breadcrumbs__list so that it displays correctly in Safari and print.
Also removed my name from the packages.json. I don't want to take credit for that monstrosity. 😉
=> POWR-1707 small set of sane print defaults

web/themes/custom/cloudy/templates/content/alert/node--alert--featured.html.twig, web/themes/custom/cloudy/webpack.config.js
**This PR fixes an issue where webpack was not correctly running assets pulled from node_modules through the babel-loader (where transpiling happens).**
**To test (for local dev):**
1. Pull down MASTER, run a build, open IE and navigate to: http://portlandor.lndo.site/revenue/services/file-and-pay-your-arts-tax
1. Verify —> there are errors and tabs do not work!
1. Now, pull down this branch and run a build
1. Open IE and navigate to: http://portlandor.lndo.site/revenue/services/file-and-pay-your-arts-tax
1. Verify —> NO JS errors and tabs are working! 🎉
**To test (multi-dev):**
1. Open the multi-dev branch URL in IE11
1. Navigate to: http://portlandor.lndo.site/revenue/services/file-and-pay-your-arts-tax
1. Verify —> NO JS errors and tabs are working! 🎉
=> POWR-2002 fix(webpack): where node_modules were being excluded from transpile

.circleci/config.yml
Turn off verbose output since it didn't help identify cause of `drush cim` error.
=> POWR-2168 Some builds fail on drush cim

web/themes/custom/cloudy/cloudy.libraries.yml, web/themes/custom/cloudy/pattern-lab/_meta/_01-foot.twig, web/themes/custom/cloudy/webpack.config.js
This splits up the main cloudy entry point so there is separate entry for scss & js – making the watch re-renders much quicker!
=> POWR-1980 build: optimize WebPack by splitting Scss & Js entry

web/sites/default/config/views.view.group_media.yml, web/sites/default/config/views.view.media.yml, web/sites/default/config/views.view.media_library.yml, web/sites/default/config/views.view.my_media.yml
This PR includes updates to the following views:
* Admin Media
* Admin Group Media
* My Media
* Media Library (not in use, but updated for future use)
The following fields are now used in the combined filters for these media types:
- Audio + Video
-- Name
-- Title
-- Transcript
-- Caption
- Image
-- Name
-- Caption
- Document
-- Name
-- Summary
- Map + Chart
-- Name
-- Summary
Also, by way of refactoring, I’ve deleted some Admin Media view displays that I had disabled some time ago. I disabled them to verify that they were no longer in use and no one would notice their absence.
=> POWR-2259 added summary field to combined fields filter for all media views

web/themes/custom/cloudy/src/cloudy.scss, web/themes/custom/cloudy/src/css/_print.scss
**This PR provides a fix for the way that Firefox incorrectly handles the printing of flexbox wrappers.**
**To Test:**
1. **In Chrome —>** Navigate to https://powr-2137-portlandor.pantheonsite.io/bps/fix-it-fairs/events/2020/2/29/fix-it-fair-floyd-light-middle-school
2. Print preview the page to get an idea of how the general print layout should look and feel
3. **In Firefox —>** Navigate to https://powr-2137-portlandor.pantheonsite.io/bps/fix-it-fairs/events/2020/2/29/fix-it-fair-floyd-light-middle-school
1. Print preview the page —> verify the result is nearly the same as Chrome (no huge white space gaps breaking up pages)
=> POWR-2137: FIX Firefox not properly handling flexbox items on print

web/themes/custom/cloudy/src/css/_pages.scss
**This PR adds a fix where IE incorrectly handles single direct children of flexbox wrappers that would, in normal conditions, expand to full width.**
Was a bit tricky to track down! :-)
**To test:**
1. Visit https://powr-1881-portlandor.pantheonsite.io/ in IE
2. Visit the same site on Chrome —> Verify the homepage 3-column section is the same
=> POWR-1881: Homepage IE flexbox issues

web/themes/custom/cloudy/src/components/_form.scss, web/themes/custom/cloudy/src/layouts/drawer/drawer.scss
This PR fixes an issue where on iOS Safari — the native browser adds a bottom floating navbar which, if not handled properly, hides content below.
**Testing/UAT:**
1. On iPhone sim OR a native iPhone, navigate to —> https://powr-2430-portlandor.pantheonsite.io/news
1. Toggle the filter
1. Scroll down to the very last item in the filter
1. Click the "Show more" toggle —> Verify —> user is able to toggle more/less items
=> POWR-2430: Last element in drawer does not trigger on mobile

web/modules/custom/portland/modules/portland_file_replace/portland_file_replace.module, web/sites/default/config/field.field.media.chart.field_display_groups.yml
Added a null ref check to fix the error, and also discovered that field_display_groups is not required on Chart media type. Not populating this field would cause a media item to be inaccessible to a group editor.
=> POWR-2436 - Notice related to portland_file_replace on add new media

web/themes/custom/cloudy/src/layouts/drawer/drawer.scss
This pr removes the drawer scrollbar on desktop while preserving the padding accounting for iOS Browser UI.
**Test**
1. Visit [https://powr-2490-portlandor.pantheonsite.io/](https://powr-2490-portlandor.pantheonsite.io/)
2. Verify iOS Browser UI does not overlap the facets on mobile.
3. Verify scrollbar no longer appears on desktop.
=> POWR-2490 fix: Remove drawer scrollbar on desktop

web/sites/default/config/block.block.cloudy_copyrightblock.yml, web/themes/custom/cloudy/templates/block/block--system-branding-block.html.twig
This fixes the redundant alt text in the site logo and updates the footer city seal alt text.
**Test**
1. Visit [https://powr-2260-portlandor.pantheonsite.io/](https://powr-2260-portlandor.pantheonsite.io/)
2. Verify that site logo alt text is no longer reading "Image Image"
3. Verify footer city seal alt text has been updated to "Portland City Seal"
=> POWR-2260 fix: site logo and footer seal alt text

web/sites/default/config/field.field.node.city_charter.field_charter_parent.yml, web/sites/default/config/field.field.node.city_code.field_code_parent.yml, web/sites/default/config/views.view.entity_reference_views_charter_code_parent.yml
By using an entity reference view for the autocomplete selection on field_code_parent and field_charter_parent, a non-administrator can still select unpublished content in the entity reference. It is important to turn off SQL rewriting to prevent persisting permission issues.
=> POWR-2526 Use entity ref view on  charter/code parent field

web/sites/default/config/core.extension.yml
This story will be in 2 branches. This first branch uninstalls the module and is used for thoroughly testing the replacement datepicker. The widget was switched to the built-in HTML5 option in an earlier story that has already been merged, but it merits a full run through QA before completely ripping out the bootstrap datepicker.
The 2nd branch is POWR-2589-2 with a separate PR.
=> POWR-2589 uninstall bootstrap_datepicker

web/modules/custom/portland/portland.tokens.inc, web/sites/default/config/field.field.media.chart.image.yml, web/sites/default/config/field.field.media.document.field_document.yml, web/sites/default/config/field.field.media.image.image.yml, web/sites/default/config/field.field.media.map.field_geo_file.yml, web/sites/default/config/field.field.media.map.field_map_file.yml, web/sites/default/config/field.field.media.map.image.yml
Media entity file uploads now all use a year subdirectory. Custom group-path token was removed.
=> POWR-2839 Removed group-path custom token

web/sites/default/config/core.extension.yml, web/sites/default/config/rabbit_hole.behavior_settings.media_type_document.yml, web/themes/custom/cloudy/templates/field/field--media--field-document.html.twig, web/themes/custom/cloudy/templates/field/file-link.html.twig
* Remove Rabbit Hole settings on media document
* Uninstall Rabbit Hole media submodule (files are part of parent RH module and do not need to be removed in a follow-up deploy)
* Revert changes to 2 template files
=> POWR-2853 Revert faux-permalink functionality for documents

web/sites/default/config/field.field.node.council_document.field_efiles_link.yml, web/sites/default/config/field.field.node.event.field_web_conference_link.yml
Set link fields for Efiles and webinars to accept external links only, in hopes this may cut down on validation issues for editors.
=> POWR-2860 link field validation

composer.json
Used a patch to resolve error. I was unable to figure out why Sitewide Editor role had the problem but none other, and was unable to really understand the issue, but the patch fixes it.
Patch: https://www.drupal.org/files/issues/page_manager.page_access_wsod_fix.patch
Issue page: https://www.drupal.org/project/page_manager/issues/2837833
=> POWR-3380 fix dashboard_user missing context error

web/sites/default/config/views.view.city_charter.yml
This wording is from the summary of the Charter Commission group. Also removed the unused migration message.
=> POWR-3467 Add reference to Charter Commission on City Charter page

tests/percy/package.json, tests/percy/yarn.lock
This PR updates browserslist to the patched version.
I did not upgrade our theme dependencies due to complexity, and think it should be a separate story.
@joshuami let me know if you'd like me to add auditing/upgrading theme dependencies to Jira, or anything you'd like to add.
=> POWR-3545 Upgrade browserslist to version 4.16.5 or later to fix security vulnerability

web/sites/default/config/views.view.admin_groups.yml, web/sites/default/config/views.view.admin_groups_social_media_audit.yml
This PR adds a logo field to the groups view, as well as a separate view for the upcoming social media audit this sprint.
=> POWR-3534 Social media / bureau logo audit views

web/sites/default/config/core.entity_form_display.group.project.default.yml, web/sites/default/config/core.entity_form_display.node.construction_project.default.yml
I'm not sure which module is responsible for the config settings here (Geofield, the Geocoder plugin for Geofield, or Leaflet), but the config structure changed and Drupal didn't recognize the existing config as being out of date. I fonzied it and got it working--changed the default market setting to something else, then changed it back. After that the point marker tool appeared, and the config changed. Or maybe the node field display settings just needed to be re-saved. Anyway, it's working now.
=> POWR-3806 - fix construction and project Geo Map fields to show point marker tool

web/sites/default/config/core.entity_form_display.node.city_service.default.yml, web/sites/default/config/core.entity_view_display.node.city_service.default.yml, web/sites/default/config/core.entity_view_display.node.city_service.featured.yml, web/sites/default/config/core.entity_view_display.node.city_service.related.yml, web/sites/default/config/core.entity_view_display.node.city_service.search_result.yml, web/sites/default/config/core.entity_view_display.node.city_service.teaser.yml, web/sites/default/config/field.field.node.city_service.field_webform.yml, web/sites/default/config/field.storage.node.field_webform.yml, web/sites/default/config/webform.webform.report_campsite_or_vehicle.yml, web/themes/custom/cloudy/templates/content/city-service/node--city-service--full.html.twig
There is one config file that may seem out of place. I removed the manually-added required field indicator in the campsite reporting form. It was showing two indicators, since the built-in one is also turned on.
=> POWR-3968 implement webform as entity reference field in Service content type

composer.json, composer.lock, web/sites/default/config/field.field.group.advisory_group.field_address.yml, web/sites/default/config/field.field.group.program.field_address.yml, web/sites/default/config/field.field.group.project.field_address.yml, web/sites/default/config/group.role.advisory_group-4f5146610.yml, web/sites/default/config/group.role.bureau_office-4f5146610.yml, web/sites/default/config/group.role.elected_official-4f5146610.yml, web/sites/default/config/group.role.program-4f5146610.yml, web/sites/default/config/group.role.project-4f5146610.yml, web/sites/default/config/language/vi/views.view.content_translations.yml, web/sites/default/config/language/zh-hans/views.view.content_translations.yml, web/sites/default/config/system.action.user_add_role_action.translator.yml, web/sites/default/config/system.action.user_remove_role_action.translator.yml, web/sites/default/config/user.role.administrator.yml, web/sites/default/config/user.role.alert_editor.yml, web/sites/default/config/user.role.neighborhood_editor.yml, web/sites/default/config/user.role.sitewide_editor.yml, web/sites/default/config/user.role.support_agent.yml, web/sites/default/config/user.role.translator.yml
I'm also including a Translation Management patch that will allow us create a translation job and export the actions and topcis taxonomy terms. (Due to previous bug we had to manually export them to CSV.)
=> POWR-4016 Create translator role and permissions

web/sites/default/config/webform.webform.website_feedback.yml
Updates to the Website Feedback form:
* Added Agent Use Only field block
* Removed Reason for Contact, replaced with Ticket Type and conditional logic to set value
* Tweaks to body of email submission to Webform with new fields
Triggers have been added to Zendesk to set Contact Type and Ticket Type in an abstract way, for any ticket created by email handler.
=> CSM-140 added Agent Use Only field block to feedback form

composer.json, composer.lock, web/modules/custom/portland/modules/portland_zendesk/src/Plugin/WebformHandler/ZendeskHandler.php, web/modules/custom/portland/modules/portland_zendesk/src/Plugin/WebformHandler/ZendeskUpdateHandler.php, web/sites/default/config/webform.webform.report_e_scooter.yml, web/sites/default/config/webform.webform.zendesk_api_test.yml
* ZendeskHandler.php and ZendeskUpdateHandler.php were updated to support both a Ticket Group and Ticket Assignee field
* The E-scooter report webform was updated to set the group on creation
* E-scooter Riding on Sidewalk reports configured to create ticket as Solved and assign to service account user
* Logic added to e-scooter form config to disable sending vendor notifications if no computed address is present (in the case of user not knowing which company)
* Zendesk API Test webform updated to only allow access to Administrator and Support Agent roles
* API Test webform updated to support updating tickets if ticket ID is provided, allowing both API handlers (create and update) to be tested
* Updated views_bulk_operations module because it's unsupported and blocking builds
=> CSM-160 Update portland_zendesk module to set assignee groups instead of individuals

.circleci/config.yml
Once this is merged, we need to check whether the csm-173 multidev is deleted before closing the story.
Also, there is a csm-173a branch that needs to be merged, and verify that that multidev is also deleted.
=> CSM-173 Update build script to also remove csm environments on merge

web/sites/default/config/system.site.yml, web/sites/default/config/webform.webform.3_1_1_regional_testing.yml
Two very small fixes:
* Updated the website address to no longer use the outdated powr@portlandoregon.gov
* Fixed the 311 Regional Testing form to use the correct field ID for the requester when sending the report to Zendesk.
=> CS-307 change site email address, fix sender in 311 Regional Testing form

web/sites/default/config/views.view.zendesk_tickets.yml
Very small change; added a Zendesk API query parameter to exclude graffiti tickets from the Developer Test Group in the view that feeds the graffiti map.
=> CS-383 bug fix to prevent test tickets from appearing on the graffiti map

web/sites/default/config/language/es/views.view.electeds.yml, web/sites/default/config/language/ru/views.view.electeds.yml, web/sites/default/config/language/vi/views.view.electeds.yml, web/sites/default/config/language/zh-hans/views.view.electeds.yml, web/sites/default/config/views.view.electeds.yml, web/sites/default/config/webform.webform.contact_elected.yml
- Updated elected entity reference views to filter by site default language, rather than current interface language. This was causing the Spanish version of the form to only show the one commissioner that had a translated group.
- Updated active elected reference machine name
- Changed webform to simply use the view results of the elected view, rather than an entity select form element, for cases where it's sending the email to all officials/commissioners.
=> PGOV-833 Refactor email logic for contact_elected form

web/modules/custom/portland/modules/portland_zendesk/src/Element/PortlandSupportAgentWidget.php, web/sites/default/config/webform.webform.3_1_1_regional_testing.yml, web/sites/default/config/webform.webform.location_widget_test_open_reques.yml, web/sites/default/config/webform.webform.report_camp_removal_complaint.yml, web/sites/default/config/webform.webform.report_discrimination.yml, web/sites/default/config/webform.webform.report_e_scooter.yml, web/sites/default/config/webform.webform.report_graffiti.yml, web/sites/default/config/webform.webform.report_graffiti_resolution.yml, web/sites/default/config/webform.webform.report_parks_issue.yml, web/sites/default/config/webform.webform.report_trash_can.yml, web/sites/default/config/webform.webform.request_ada_accommodation.yml, web/sites/default/config/webform.webform.website_feedback.yml
* Made sure all radio/checkboxes have same value/text (previously some were abbreviated)
* Updated incorrect conditional logic to display elements and in computed twig 
* Changed policy issues to checkboxes-other (previously radios)
UPDATE:
* Disabled Escalate checkbox on live forms where not specifically requested
* Fixed logic in graffiti form that was causing hidden hate speech field to be required even though hidden
* Removed email input mask from Campsite Removal Complaint and Report Discrimination form witness email fields and replaced with pattern
=> CS-675 ranger form updates, added escalation checkbox to CSUO block

web/libraries_js/fpdr/pensionCalc.js
once is unnecessary here because the script is loaded from an import_js function within the webform, so the HTML will always be loaded by that point.
=> PGOV-1012 Fix FPDR pension calculator

web/sites/default/config/webform.webform.cable_complaint_resolution.yml, web/sites/default/config/webform.webform.report_cable_complaint.yml, web/sites/default/config/webform.webform.report_parks_issue.yml
* Add url_encode filter to all element values being used in the Resolution URL
* Make resolution comment on ticket a private note
* UNRELATED: Add missing conditional logic to prevent Park Safety reports from going into Developer Test Group when test submission box is not checked
=> SIT-959 bug fix for Cable Complaints resolution form

web/modules/custom/portland/modules/portland_location_picker/README.md, web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js, web/modules/custom/portland/modules/portland_location_picker/src/Plugin/WebformElement/PortlandLocationPicker.php, web/sites/default/config/webform.webform.report_park_maintenance_issue.yml
* Configure form to use new regions GeoJSON layer and capture region ID
* Refactor location widget to allow webform editors to specify the name of the property that contains the region value we want to capture (defaults to 'region_id')
=> SIT-977 Update park maintenance form to identify park zone region name

web/sites/default/config/webform.webform.report_row_obstruction.yml
* Make computed email recipient element visible to authenticated users - had to create a 2nd copy of the element because disabling the original for anonymous users would break the routing
* Change all instances of "right of way" to be hyphenated
=> SIT-1034 ROW Obstruction updates

web/modules/custom/portland/modules/portland_location_picker/js/portland_location_picker.js, web/sites/default/config/webform.webform.report_graffiti.yml
* Fixed a bug in the location widget that prevents an incidents layer from coexisting with a regions-type primary layer
* Added the park maintenance zones layer to the widget on graffiti reports
=> SIT-1094 Graffiti Form 2.2 - add park maintenance zone support

web/modules/custom/portland/modules/portland_address_verifier/js/addressVerifierModel.js, web/modules/custom/portland/modules/portland_address_verifier/js/addressVerifierView.js, web/modules/custom/portland/modules/portland_address_verifier/src/Element/PortlandAddressVerifier.php, web/modules/custom/portland/modules/portland_address_verifier/src/Plugin/WebformElement/PortlandAddressVerifier.php, web/sites/default/config/subpathauto.settings.yml, web/sites/default/config/webform.webform.report_parks_incident.yml, web/sites/default/config/webform.webform.report_row_obstruction.yml
This branch includes an update to the Address Verifier widget that adds an API call to retrieve the taxlot ID number. I thought it would be needed for the ROW form, but turns out it's not. However, I decided to leave the functionality in so it can be used later. It has to be activated using a custom parameter. 
There is also one update to the parks incident reporting form, to hide the Internal Use Only block from anonymous users.
=> ROW Compliance | Form 1.4

web/modules/custom/portland/modules/portland_ecouncil/portland_ecouncil.module, web/sites/default/config/views.view.electeds.yml, web/sites/default/config/views.view.manage_council_documents.yml, web/themes/custom/cloudy/templates/field/file-link.html.twig
- don't show inactive electeds in agenda item voting list
- redirect back to council president view after adding recommendation
- add back document--download class to file-link template, used for GA4 tracking
- Also remove target=”_blank” that was added in a previous PR
=> PGOV-1344 fix error in CKEditor document browser

web/sites/default/config/webform.webform.contact_elected_official_2025.yml
* Added email handler for each inbox to be used in send-all use case, instead of using delimited list of emails in one handler. This is to fix the issue with Zendesk only generating one ticket.
=> PGOV-1363 Contact Elected Official form v2.2 updates
